sudo: enabled
branches:
  only:
    - master
    - Development
matrix:
  include:
    - name: SpringBootBackend
    - language: java
      jdk: oraclejdk9
      services:
        - postgresql
      addons:
        postgresql: "9.5"
      before_script:
        - cd Backend/eishms
        - psql -c 'create database consumptiondb;' -U postgres
        - sudo -u postgres psql -c "ALTER ROLE postgres WITH password '12345';"
      script:
        - ./gradlew build --info
    - name : AngularFrontEnd
    - language: node_js
      node_js:
        - "stable"
      dist: trusty
      sudo: required

      branches:
        only:
          - master
          - Development
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd Frontend
        - npm install
      script:
      #   - ng lint
        - ng build
      #  - ng serve
      #deploy:
      #  provider: heroku
      #  api_key:
      #    secure: 7f504e09-2888-4583-a328-e953228f4213
      #  app: eish-ui      
    - name: EISHSimulations
    - language: node_js
      node_js: 
        - "stable"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd "Device Simulations"    
      script:
        - npm run   
