language: java
name: SpringBoot
jdk: oraclejdk11
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - cd Backend/eishms
  - psql -c 'create database eishdb;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password '12345';"
script:
  - ./gradlew build --info
