sudo: enabled
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      addons:
        postgresql: "9.5"
      before_script:
        - cd Backend/eishms
        - psql -c "create database consumptionDB;" -U postgres
        - sudo -u postgres psql -c "ALTER ROLE postgres WITH password '12345'" 
      script:
        - ./gradlew build
      services:
        - postgresql

    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required

      branches:
        only:
          - master

      before_script:
        - cd Frontend
        - npm install -g @angular/cli
      script:
        - ng lint
        - ng build
      deploy:
        provider: heroku
        api_key:
          secure: 7f504e09-2888-4583-a328-e953228f4213
        app: eish-ui      

    - language: node_js
      node_js: 
        - "stable"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd "Device Simulations"    
      script:
        - npm run test  